- block:
  - name: Create credentials Folder
    file:
      path: /credentials
      state: directory

  - name: Write Databases Password
    template:
      src: password.txt.jinja2
      dest: /credentials/password.txt
      mode: 0640

- name: Copy Init Script
  template:
    src: init.sh.jinja2
    dest: /credentials/init.sh
    mode: 0750
    
- name: Copy init_password.service
  template:
    src: init-password.service.jinja2
    dest: /lib/systemd/system/init-password.service
    
- name: Enable service
  service:
    name: init-password
    enabled: yes
