- block:
  - name: Create credentials Folder
    file:
      path: /credentials
      state: directory

  - name: Write Databases Password
    template:
      src: password.txt.jinja2
      dest: /credentials/password.txt
      mode: 644
  when: init_db.docker is undefined

- name: Copy Init Script
  template:
    src: init.sh.jinja2
    dest: /tmp/init.sh
    mode: 0750
    
- name: Copy init_password.service
  template:
    src: init_password.service
    dest: /usr/lib/systemd/system/init-password.service
    mode: 0644
    
- name: Enable service
  service:
    name: init_password
    enabled: yes
