- block:
  - name: Create credentials Folder
    file:
      path: /credentials
      state: directory

  - name: Write Databases Password
    template:
      src: password.txt.jinja2
      dest: /credentials/password.txt
      mode: 0640

- name: Copy Init Script
  template:
    src: init.sh.jinja2
    dest: /credentials/init.sh
    mode: 0750
    
- name: Copy init_password.service
  template:
    src: init-password.service.jinja2
    dest: /lib/systemd/system/init-password.service

- name: Enable service
  service:
    name: init-password
    enabled: yes

- block: 
  - name: Check init password, if /credentials/* file not exist or no content, stop and exit Ansible
    shell: |
      [  -s /credentials/password.txt ] && [  -s /credentials/init.sh ] && init_initpasswd=true || init_initpasswd=false
      echo $init_initpasswd
    register: init_password_check

  - name: Output error when init password fail
    fail: msg="init_password role is not done,exit!"
    when: init_password_check.stdout == "false"
