- block:
  - name: Create credentials Folder
    file:
      path: /credentials
      state: directory

  - name: Write Databases Password
    template:
      src: password.txt.jinja2
      dest: /credentials/password.txt
      mode: 0640

- name: Copy Init Script
  template:
    src: init.sh.jinja2
    dest: /credentials/init.sh
    mode: 0750
    
- name: Copy init_password.service
  template:
    src: init-password.service.jinja2
    dest: /lib/systemd/system/init-password.service

- name: Judge file is empty
  shell: |
    [  -s /credentials/password.txt ] && [  -s /credentials/init.sh ] && init_initpasswd=true || init_initpasswd=false
    echo $init_initpasswd
  register: init_initpasswd
  
# if initpass is null or initpasswd file is not exist , stop and exit
- name: Check php_initpasswd
  fail: msg="init_password role is not done,exit!"
  when: init_initpasswd.stdout == "false"
    
- name: Enable service
  service:
    name: init-password
    enabled: yes
