- block:
  - name: Create credentials Folder
    file:
      path: /credentials
      state: directory

  - name: Write Databases Password
    template:
      src: password.txt.jinja2
      dest: /credentials/password.txt
      mode: 644
  when: init_db.docker is undefined


- name: Copy Init Script
  template:
    src: init.sh.jinja2
    dest: /tmp/init.sh
    mode: 0750
